version: '3'
services:
  Restaurantsdb:
    image: postgres
    container_name: restaurantsdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=restaurantsdb
    ports:
      - 5433:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
